### ISSUE TITLE
包过期不再维护，会不会影响后续长久使用？

### ISSUE THREAD

**Issue by alexyuetmout** [Yurunsoft/Guzzle-Swoole#13]
![image](https://user-images.githubusercontent.com/25193846/74508638-79e57600-4f3a-11ea-8f60-5f0131763c8a.png)

**Comment by Yurunsoft** [comment]
不影响的，由于`ElasticSearch`的客户端是用的`guzzlehttp/ringphp`，统一在这个包里实现`Swoole`化。

这两个包只是不维护，还是可以正常使用的。
