### ISSUE TITLE
https 请求报错

### ISSUE THREAD

**Issue by alexyuetmout** [Yurunsoft/Guzzle-Swoole#14]
![image](https://user-images.githubusercontent.com/25193846/74509945-a77fee80-4f3d-11ea-9c68-49d3f6979a6a.png)
![image](https://user-images.githubusercontent.com/25193846/74509954-ab137580-4f3d-11ea-8565-8fcbbfa1731a.png)
在`imi`中使用，`Main`里面设置了处理器了，请求`https`就会报错
![image](https://user-images.githubusercontent.com/25193846/74509999-c41c2680-4f3d-11ea-8e7f-2c813f83e29f.png)
`http`没问题

**Comment by Yurunsoft** [comment]
我这边测试没有问题，你看下 `SwooleHandler` 是不是：`\Yurun\Util\Swoole\Guzzle\SwooleHandler`

**Comment by alexyuetmout** [comment]
![image](https://user-images.githubusercontent.com/25193846/74510959-d5663280-4f3f-11ea-9675-abd39237af0f.png)
![image](https://user-images.githubusercontent.com/25193846/74511021-f6c71e80-4f3f-11ea-9060-cc8423bdcfd1.png)
![image](https://user-images.githubusercontent.com/25193846/74511072-13fbed00-4f40-11ea-9cca-cf4deaa7e757.png)

**Comment by Yurunsoft** [comment]
Swoole 版本多少？

**Comment by alexyuetmout** [comment]
![image](https://user-images.githubusercontent.com/25193846/74511637-62f65200-4f41-11ea-8517-b1943ef37bde.png)

**Comment by Yurunsoft** [comment]
用 strace 工具跟踪一下 worker 进程吧，使用方法：<http://wiki.swoole.com/wiki/page/202.html>

日志贴一下

**Comment by alexyuetmout** [comment]
这个要等好久么~ mac 上面没看到有输出到文件的

**Comment by Yurunsoft** [comment]
strace 跟踪 worker 进程后，访问接口，进程崩了就可以看日志了

**Comment by alexyuetmout** [comment]
![image](https://user-images.githubusercontent.com/25193846/74518824-74def180-4f4f-11ea-87ba-24bee0f6581e.png)

是这个东西吗?我看到这两个总会出现,其他就和上面一句一样一直在扫描

**Comment by Yurunsoft** [comment]
只需要访问接口，然后worker进程崩溃后，就可以ctrl+c停止，然后提供一下日志，我给swoole开发组大佬看看是什么情况

**Comment by alexyuetmout** [comment]
![image](https://user-images.githubusercontent.com/25193846/74519517-ccca2800-4f50-11ea-9c3a-65b3abc58843.png)
![image](https://user-images.githubusercontent.com/25193846/74519527-d5baf980-4f50-11ea-99e3-9366ec3bb9f3.png)
![image](https://user-images.githubusercontent.com/25193846/74519538-dce20780-4f50-11ea-88b3-15c862156cdc.png)
我找到一个这个

**Comment by Yurunsoft** [comment]
@twose 大佬麻烦看下

**Comment by twose** [comment]
什么系统 是MacOS么 不是的话用valgrind看一下
openssl 库是怎么装的? 是否有问题?

**Comment by twose** [comment]
SIGBUS一般是内存没对齐吧 是几位的操作系统 openssl库是不是不匹配或者损坏的?

**Comment by alexyuetmout** [comment]
mac 系统 就用的内置的 
![image](https://user-images.githubusercontent.com/25193846/74520303-3860c500-4f52-11ea-8ada-2a786265d659.png)

**Comment by twose** [comment]
brew装的吧
重新装一下openssl库
从头编译swoole

**Comment by alexyuetmout** [comment]
![image](https://user-images.githubusercontent.com/25193846/74520525-b6bd6700-4f52-11ea-8078-c8df513ce492.png)

**Comment by alexyuetmout** [comment]
好的 我试试
