### ISSUE TITLE
GuzzleHttp\Exception\ConnectException: Connect error -1: Connect failed

### ISSUE THREAD

**Issue by alexyuetmout** [Yurunsoft/Guzzle-Swoole#15]
添加`swoolehandler` 返回的结果是
![image](https://user-images.githubusercontent.com/25193846/74525248-9b0a8e80-4f5b-11ea-8bf2-7c8ced986223.png)
去掉`handler`使用原生的返回结果是
![image](https://user-images.githubusercontent.com/25193846/74525293-b1184f00-4f5b-11ea-9980-9e72dcbb789a.png)
`handler`的添加
![image](https://user-images.githubusercontent.com/25193846/74525303-b9708a00-4f5b-11ea-8563-fbf87985e3ce.png)
注释掉就正常

**Comment by Yurunsoft** [comment]
请求代码是？

**Comment by alexyuetmout** [comment]
![image](https://user-images.githubusercontent.com/25193846/74525644-811d7b80-4f5c-11ea-99aa-28a00fd5f056.png)

**Comment by alexyuetmout** [comment]
除了处理器应该是跟原生写法都一样的吧 ,我在`Main`里面设定了处理器就不可以了

**Comment by Yurunsoft** [comment]
`timeout`调大

**Comment by alexyuetmout** [comment]
多少合适,3 5 10 都不行,而且太长了也不好吧

**Comment by Yurunsoft** [comment]
我这边3秒没有问题

**Comment by alexyuetmout** [comment]
![image](https://user-images.githubusercontent.com/25193846/74526329-1ec57a80-4f5e-11ea-8110-3ead785b3d4e.png)
![image](https://user-images.githubusercontent.com/25193846/74526364-2d139680-4f5e-11ea-91ce-e7be71d29b2e.png)
试了下好像还是连接失败 愁人

**Comment by Yurunsoft** [comment]
composer 里的版本改成 `dev-master`，现在提示会是：`Connect failed: errorCode: 111, errorMessage: Connection refused`
你看下`errorCode`和`errorMessage`

**Comment by alexyuetmout** [comment]
```
Connect failed: errorCode: 705, errorMessage: Unknown error: 705
```

**Comment by Yurunsoft** [comment]
@Twose 大佬

**Comment by twose** [comment]
`php --ri swoole`

**Comment by alexyuetmout** [comment]
![image](https://user-images.githubusercontent.com/25193846/74624027-d71f3880-5181-11ea-8801-b475331f624b.png)

**Comment by alexyuetmout** [comment]
大佬们能帮忙看下这个问题么

**Comment by twose** [comment]
请使用swoole_strerror来解析错误码 对应的是dns解析超时

你的dns服务器太慢了, 把超时参数调大 (v4.5以下默认dns解析超时为1秒, v4.5后默认为永不超时)

**Comment by alexyuetmout** [comment]
这个设置在哪里吗?我本地么

**Comment by Yurunsoft** [comment]
未使用`swoole_strerror`解析错误码，导致的错误提示文字问题，已在依赖包中修复：https://github.com/Yurunsoft/YurunHttp/commit/c89be0e201f25e456be5bb20fcdb92ed72644a78

更新一下包就行了。
