### ISSUE TITLE
证书的设置没有考虑只为路径的情况

### ISSUE THREAD

**Issue by browningweb** [Yurunsoft/Guzzle-Swoole#16]
https://github.com/Yurunsoft/Guzzle-Swoole/blob/9461074d494bdb6f11ddaa2f9367fe5f99c618da/src/SwooleHandler.php#L48

[cert描述](https://guzzle-cn.readthedocs.io/zh_CN/latest/request-options.html#cert) ：`设置成指定PEM格式认证文件的路径的字符串，如果需要密码，需要设置成一个数组，其中PEM文件在第一个元素，密码在第二个元素。`

[ssl_key描述](https://guzzle-cn.readthedocs.io/zh_CN/latest/request-options.html#ssl-key)`指定一个链接到私有SSL密钥的PEM格式的文件的路径的字符串。 如果需要密码，设置成一个数组，数组第一个元素为链接到私有SSL密钥的PEM格式的文件的路径，第二个元素为认证密码。`

**Comment by Yurunsoft** [comment]
非常感谢，v1.1.x、v2.0.x 下都已修复
