### ISSUE TITLE
composer 安装最后autoload的时候报错

### ISSUE THREAD

**Issue by pslxx** [Yurunsoft/Guzzle-Swoole#28]
![image](https://user-images.githubusercontent.com/8417207/146208414-161daa7e-f32b-4d10-8551-3c453b761d57.png)
环境: PHP7.4 Laravel8.29 Swoole 4.8.3

**Comment by agengdp** [comment]
I got same issues using php8.0 & Laravel 8.0

**Comment by Yurunsoft** [comment]
@pslxx 引入时报错不影响实际运行使用。引入时报错问题已经在 v2.2.4 版本解决。

@agengdp The error reported by composer require does not affect the actual operation. The problem of composer require error has been solved in the v2.2.4 version.

**Comment by Yurunsoft** [comment]
推荐使用 Swoole v4.8 的 native hook curl

It is recommended to use native hook curl of Swoole v4.8

http://wiki.swoole.com/#/runtime?id=swoole_hook_native_curl
