### ISSUE TITLE
 代理如何设置

### ISSUE THREAD

**Issue by excxapp** [Yurunsoft/Guzzle-Swoole#8]
请问proxy 代理用法怎么设置，guzzle方法代理没生效。
微信要求ip因此需要代理。
请问需要如何设置

**Comment by Yurunsoft** [comment]
用法和guzzle一致，是支持的，能否提供复现代码

**Comment by excxapp** [comment]
貌似是http代理https就直接忽略代理了。
![image](https://user-images.githubusercontent.com/4355581/67281790-cd066980-f502-11e9-87d0-875fcd8c10a7.png)
![image](https://user-images.githubusercontent.com/4355581/67281828-e60f1a80-f502-11e9-9316-8a41db62abc3.png)

**Comment by excxapp** [comment]
Status code must be an integer value between 1xx and 5xx.
方便加个微信调试一下吗。
代理之后直接就报错了。
微信：easyxcx

**Comment by Yurunsoft** [comment]
这个问题我明天来看一下，方便的话加个QQ群吧：17916227

**Comment by excxapp** [comment]
不加hander情况下，是可以正常进行代理，加了之后就无法代理。

**Comment by Yurunsoft** [comment]
应该是swoole不支持，我已经反馈了这个问题，等待他们解决

**Comment by excxapp** [comment]
ok

**Comment by Yurunsoft** [comment]
你的代理是否是`HTTP/1.0`，如果不确定尝试使用

`curl -v -x 127.0.0.1:808 http://api.weixin.qq.com/sns/oauth2`

把结果贴给我

`127.0.0.1:808`就是代理IP和端口，改成你自己的

**Comment by excxapp** [comment]
.weixin.qq.com/sns/oauth2
*   Trying ##隐藏IP##...
* TCP_NODELAY set
* Connected to##隐藏IP## port 10880 (#0)
> GET http://api.weixin.qq.com/sns/oauth2 HTTP/1.1
> Host: api.weixin.qq.com
> User-Agent: curl/7.54.0
> Accept: */*
> Proxy-Connection: Keep-Alive
>
* Empty reply from server
* Connection #0 to host ##隐藏IP## left intact
curl: (52) Empty reply from server

**Comment by Yurunsoft** [comment]
Swoole 4.4.9 已经修复问题了，更新一下试试吧
